# Generated by Django 5.2 on 2025-04-28 15:47

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0004_service_date_alter_service_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='is_sold',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_loan', models.BooleanField()),
                ('annual_interest_rate', models.DecimalField(decimal_places=2, max_digits=6, null=True)),
                ('total_cost', models.BigIntegerField()),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='cars.car')),
            ],
        ),
        migrations.DeleteModel(
            name='Payment',
        ),
    ]
