# Generated by Django 5.2 on 2025-04-28 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0005_car_is_sold_transaction_delete_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='loan_amount',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='tenor',
            field=models.IntegerField(null=True),
        ),
    ]
