# Generated by Django 5.2 on 2025-04-28 19:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0006_transaction_loan_amount_transaction_tenor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='total_cost',
        ),
        migrations.AddField(
            model_name='transaction',
            name='down_payment',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='car',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='cars.car'),
        ),
    ]
